#!/bin/bash

set -eu

cat << EOF > /usr/local/etc/php/conf.d/general.ini
[php]
display_errors = on
error_reporting = E_ALL
EOF

composer install -q

wait-for-it -q redis:6379

exec phpunit --log-junit /code/work/junit.xml --bootstrap test/config/phpredis.php test/test
