#!/bin/bash

set -eu

cat << EOF > /usr/local/etc/php/conf.d/general.ini
[php]
display_errors = on
error_reporting = E_ALL
EOF

# Modify tests written by pantheon-systems/wp-redis.
wp_redis_test=test/test/wp-redis/CacheTestCase.php
tmp_cache="$(mktemp)"
cp /src/wp-redis/tests/phpunit/test-cache.php "$tmp_cache"
patch -s "$tmp_cache" "$wp_redis_test.patch"
if [ ! -e "$wp_redis_test" ] || [ "$(< "$tmp_cache")" != "$(< "$wp_redis_test")" ]; then
  cp "$tmp_cache" "$wp_redis_test"
  chmod 666 "$wp_redis_test"
fi

composer install -q

wait-for-it -q redis:6379

exec phpunit --log-junit /code/work/junit.xml --bootstrap test/config/phpredis.php test/test
