#!/bin/bash

set -eux

target=work/wp-redis-patch

rm -fr "$target" "$target.zip"
mkdir -p "$target"
cp -R lua object-cache.php work/object-cache.php.patch "$target"
cp env/wp_redis_version "$target/WP_REDIS_VERSION"
{
  cd work
  zip -r wp-redis-patch.zip wp-redis-patch
}
